version: "3"

services:
  db:
    env_file: .env.cmi.db
  nginx:
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/app/public:ro

  web:
    depends_on:
      - composer
    volumes:
      - ./:/app
      - ./docker/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro

  composer:
    image: composer:2.0
    working_dir: /app
    volumes:
      - ./:/app
    command: composer install --ignore-platform-reqs --no-scripts
