version: "3"

services:
  db:
    env_file: ${DB_ENV_FILE}
    image: mysql:8
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    command: --default-authentication-plugin=mysql_native_password

  nginx:
    image: gizdpe.azurecr.io/cmi-nginx:latest
    ports:
      - "80:80"
    depends_on:
      - web
    restart: always
    volumes:
      - app-data:/app/public

  web:
    image: gizdpe.azurecr.io/cmi:latest
    env_file: ${PROD_ENV_FILE}
    restart: always
    depends_on:
      - db
    volumes:
      - storage:/app/storage
      - app-data:/app/public

volumes:
  app-data:
  db-data:
  storage:
